### PR TITLE
:gift_heart: Batch mode for install

### LINKED ISSUE #20: Batch compatible install
The install command should be batch-compatible. Currently, it asks `! Rename the binary?`, which prevents automation, and batch usage.

One way to fix this may be a `--rename` (or `--as`) option for install command:

```shell
$ stew install knative-sandbox/kn-plugin-event --as kn-event
knative-sandbox/kn-plugin-event
⬇️  Downloading asset: 100% |██████████████████████████████████████████████████████████| (57/57 MB, 34.474 MB/s)        
✅ Downloaded kn-event-linux-amd64 to /home/ksuszyns/.local/share/stew/pkg
📄 Updated /home/ksuszyns/.local/share/stew/Stewfile.lock.json
✨ Successfully installed the kn-event binary in /home/ksuszyns/bin
```

Alternative, could be a format of the installation. For example:

```shell
$ stew install knative-sandbox/kn-plugin-event!kn-event
```

### PR DESCRIPTION
**Pull request by cardil**
Fixes #20

### CODE REVIEW

**Comment by cardil** [comment]
Ping @marwanhawari

**Comment by marwanhawari** [comment]
Hey @cardil thanks for making a PR! I have no idea where to start with reviewing this though lol. It's 25,000+ LOC added and 100+ files changed. I know a lot of that is `vendor/` code, but there are still too many changes for this 1 PR.

Could you break this up into smaller PRs? Ideally each PR should just do 1 thing. For example: 1 PR just for updating the original tests, 1 PR for refactoring error handling, etc. The smaller the better. Shoot for <250 LOC changed (not including `vendor/`) even if it means making 10 PRs.

Also it would be extremely helpful if you could describe in detail what you've done and _why_ you've done it. Again, this is easier when the PRs are small.

If you can make the PRs a lot smaller, it will be much easier for me to review them and it will result in a quicker turnaround.

**Comment by cardil** [comment]
> Hey @cardil thanks for making a PR! I have no idea where to start with reviewing this though lol. It's 25,000+ LOC added and 100+ files changed. I know a lot of that is `vendor/` code, but there are still too many changes for this 1 PR.

Just, what I thought. I should have predicted this would be too much for review.

> Could you break this up into smaller PRs? Ideally each PR should just do 1 thing. For example: 1 PR just for updating the original tests, 1 PR for refactoring error handling, etc. The smaller the better. Shoot for <250 LOC changed (not including `vendor/`) even if it means making 10 PRs.

I will. Although, that might not be so easy. I wanted to address #20, but while doing so, I identified plenty of places which could be adjusted. Let's see...

> Also it would be extremely helpful if you could describe in detail what you've done and _why_ you've done it. Again, this is easier when the PRs are small.

The main theme is described in linked issue #20, but I made some additional changes, so probably it makes sense to describe them.

> If you can make the PRs a lot smaller, it will be much easier for me to review them and it will result in a quicker turnaround.

Sure, sorry for this big blob.

**Comment by marwanhawari** [comment]
Closing because this is too big

**Pull request closed without merging**
